# Generated by Django 3.0 on 2020-07-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_transport_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
