# Generated by Django 3.0 on 2020-07-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_transport_manager', '0004_vehiclemanufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemanufacturer',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact Number'),
        ),
    ]
