# Generated by Django 3.0 on 2020-07-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_transport_manager', '0005_auto_20200702_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemanufacturer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/drf_transport_manager_images/manufacturer_logo/', verbose_name='Manufacturer Logo'),
        ),
    ]
