# Generated by Django 3.0 on 2020-07-03 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drf_transport_manager', '0006_vehiclemanufacturer_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportAgencyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(default='N/A', max_length=80, verbose_name='Manufacturer Name')),
                ('contact_person', models.CharField(default='N/A', max_length=80, verbose_name='Contact Person Name')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact Number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transport_agency', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Transport Agency',
                'verbose_name_plural': 'Transport Agencies',
                'ordering': ['agency_name'],
            },
        ),
    ]
