# Generated by Django 3.0 on 2020-07-14 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drf_transport_manager', '0009_vehiclestaffmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportagencymodel',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transport_agency_creator', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='vehiclemanufacturermodel',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_manufacturer_creator', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='vehiclestaffmodel',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transport_driver_creator', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='vehicletypemodel',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_types_creator', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.CreateModel(
            name='VehicleDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, default='N/A', max_length=80, null=True, verbose_name='Registration Number')),
                ('chasis_number', models.CharField(blank=True, max_length=80, null=True, verbose_name='Chasis Number')),
                ('color', models.CharField(blank=True, max_length=80, null=True, verbose_name='Color')),
                ('capacity', models.CharField(blank=True, max_length=30, null=True, verbose_name='Capacity')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/drf_transport_manager_images/vehicle_images/', verbose_name='Vehicle Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('agency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_agency', to='drf_transport_manager.TransportAgencyModel', verbose_name='Agency')),
                ('assistant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assistant', to='drf_transport_manager.VehicleStaffModel', verbose_name='Assistant')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_detail_creator', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('driver', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_driver', to='drf_transport_manager.VehicleStaffModel', verbose_name='Driver')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_manufacturer', to='drf_transport_manager.VehicleManufacturerModel', verbose_name='Vehicle Manufacturer')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_type', to='drf_transport_manager.VehicleTypeModel', verbose_name='Vehicle Type')),
            ],
            options={
                'verbose_name': 'Vehicle Detail',
                'verbose_name_plural': 'Vehicle Details',
                'ordering': ['registration_number'],
            },
        ),
    ]
