# Generated by Django 3.0 on 2020-07-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_transport_manager', '0010_auto_20200714_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemanufacturermodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='drf_transport_manager_images/manufacturer_logo/', verbose_name='Manufacturer Logo'),
        ),
    ]
